// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lumiere/Blog.tsx": () => import("../components/mockups/lumiere/Blog.tsx"),
  "./components/mockups/lumiere/Career.tsx": () => import("../components/mockups/lumiere/Career.tsx"),
  "./components/mockups/lumiere/Home.tsx": () => import("../components/mockups/lumiere/Home.tsx"),
  "./components/mockups/lumiere/Portfolio.tsx": () => import("../components/mockups/lumiere/Portfolio.tsx")
};
